[build]
builder = "nixpacks"

[deploy]
startCommand = "cd Poker_Mentor_v4/poker_mentor && python main.py"
restartPolicyType = "on_failure"

[environments]
  [environments.production]
    [environments.production.variables]
      PYTHONUNBUFFERED = "true"

# Health checks (опционально)
[[services]]
name = "web"
[http]
path = "/health"
port = 8000
initialDelaySeconds = 30
periodSeconds = 60
timeoutSeconds = 10
successThreshold = 1
failureThreshold = 3