[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd Poker_Mentor_v4/poker_mentor/app && python bot/webhook_server.py"

[[services]]
name = "web"
http_port = 8080

[build.environment]
PYTHON_VERSION = "3.11"

[service]
compute = "large"  # или "medium", "x-large" и т.д.