[build]
builder = "nixpacks"

[deploy]
startCommand = "python poker_mentor/main.py"
restartPolicyType = "on_failure"

[environments]
  [environments.production]
    [environments.production.variables]
      PYTHONUNBUFFERED = "true"

[[services]]
name = "web"
[http]
path = "/health"
port = 8000
initialDelaySeconds = 30
periodSeconds = 60
timeoutSeconds = 10
successThreshold = 1
failureThreshold = 3