version: '3.8'

services:
  poker-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=sqlite:///./poker_mentor.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped