version: '3.8'

services:
  poker-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env

  # Redis для кэширования (опционально)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped