[build]
builder = "nixpacks"

[deploy]
startCommand = "python app/main.py"

[[services]]
name = "web"
port = 8000

[[services]]
name = "postgres"
type = "postgres"

[[services]]  
name = "redis"
type = "redis"