[build]
builder = "NIXPACKS"
buildCommand = "cd poker_mentor && pip install -r requirements.txt"

[deploy]
startCommand = "cd poker_mentor && python bot/webhook_server.py"

[[services]]
name = "web"
http_port = 8080