[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd Poker_Mentor_v4/poker_mentor/app && python bot/webhook_server.py"

[build.environment]
PYTHON_VERSION = "3.11"

[[services]]
name = "web"
http_port = 8080